name: melon-ticket-check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # 每30分鐘執行一次，你可以調整

jobs:
  check-ticket:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Melon Ticket Checker
        run: node index.js
        env:
          PRODUCT_ID: ${{ secrets.PRODUCT_ID }}
          SCHEDULE_ID: ${{ secrets.SCHEDULE_ID }}
          SEAT_ID: ${{ secrets.SEAT_ID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
